### ISSUE TITLE
[Epic] Githubでユーザー登録/ログイン

### ISSUE THREAD

**Issue by 052hide** [funteractive-inc/iju-docs#18]
## 概要

ユーザーはGitHub認証を使用してユーザー登録、ログインを行えるようになる

### デザイン

- [ ] xxx

### サーバーサイド

- [ ] APIスキーマ作成
  - [ ] https://github.com/funteractive-inc/iju-backend/issues/61
  - [ ] https://github.com/funteractive-inc/iju-backend/issues/63
- [ ] 実装
  - [ ] https://github.com/funteractive-inc/iju-backend/issues/62
  - [ ] https://github.com/funteractive-inc/iju-backend/issues/64

### フロントエンド

- [ ] xxx

### Test

- [ ] xxx

### その他

- [x] https://github.com/funteractive-inc/iju-backend/issues/59
- [x] https://github.com/funteractive-inc/iju-backend/issues/60

**Comment by 052hide** [comment]
## メールアドレスの扱い

メールアドレスでユーザー登録の場合はAuth0によってメールアドレス認証される
GitHubでユーザー登録の場合は、すでに認証は終わっているのでメールアドレスの認証にAuth0はたぶん使えない

## 結論

Githubでユーザー登録した場合は一旦メールアドレスの登録をなしにする
