### ISSUE TITLE
[Epic] 初回ユーザー情報登録

### ISSUE THREAD

**Issue by 052hide** [funteractive-inc/iju-docs#19]
## 概要

ユーザー登録後、ユーザー情報を登録する

### デザイン

- [ ] xxx

### バックエンド

- [x] https://github.com/funteractive-inc/iju-backend/issues/77
- [x] https://github.com/funteractive-inc/iju-backend/issues/78
- [x] https://github.com/funteractive-inc/iju-backend/issues/79

### フロントエンド

- [ ] xxx

### Test

- [ ] xxx

### その他

- [ ] xxx

**Comment by 052hide** [comment]
どのタイミングで保存する (APIを呼び出す) かわからない

- ひとつのエンドポイントで、リクエストボディによって部分更新できるようにする
- 配列の項目の更新はなし
- 配列の項目はadditional
- 配列の項目の修正、削除も考えておかないといけない

---

Entity単位でエンドポイントを作った方がシンプルそう
Entityを跨いだ更新があるとトランザクションが効かない

## 結論

Entity単位で更新とする
仮にEntityを跨いだ更新が必要になった場合でも、致命的ではないため段階的にリファクタできる
