### ISSUE TITLE
[Epic] ユーザー情報取得

### ISSUE THREAD

**Issue by 052hide** [funteractive-inc/iju-docs#22]
### デザイン

- [ ] xxx

### バックエンド

- [x] https://github.com/funteractive-inc/iju-backend/issues/87
- [x] https://github.com/funteractive-inc/iju-backend/issues/88
- [x] https://github.com/funteractive-inc/iju-backend/issues/91
- [x] https://github.com/funteractive-inc/iju-backend/issues/92

### フロントエンド

- [x] https://github.com/funteractive-inc/iju-frontend/issues/31

### Test

- [ ] xxx

### その他

- [ ] xxx
