### ISSUE TITLE
[Epic] マイページ作成

### ISSUE THREAD

**Issue by 052hide** [funteractive-inc/iju-docs#23]
### デザイン

- [ ] マイページ

### バックエンド

- [ ] xxx

### フロントエンド

デザイン未確定のためWFを仮実装する

- [ ] 仮UI
  - [x] https://github.com/funteractive-inc/iju-frontend/issues/96
  - [ ] https://github.com/funteractive-inc/iju-frontend/issues/97
  - [ ] https://github.com/funteractive-inc/iju-frontend/issues/98
  - [ ] Formモーダルの作成、配置、API結合
- [ ] 本UI
  - [ ] マイページ
  - [ ] レジュメ更新ページ
  - [ ] アカウント設定更新ページ
  - [ ] Formモーダルの作成、配置
- [ ] API
  - [ ] https://github.com/funteractive-inc/iju-frontend/issues/115

### Test

- [ ] xxx

### その他

- [ ] xxx
